version: '3'
services:
  angular:
    build: ./Frontend  # Ruta a la carpeta de tu aplicación Angular
    ports:
      - "4200:4200"  # Mapeo del puerto del contenedor al puerto del host

  web:
    build: ./Backend  # Ruta a la carpeta de tu aplicación Flask
    ports:
      - "5000:5000"  # Mapeo del puerto del contenedor al puerto del host
    depends_on:
      - db  # Dependencia del servicio de base de datos

  db:
    image: postgres:latest  # Imagen de PostgreSQL desde Docker Hub
    ports:
      - "5435:5435"  # Mapeo del puerto del contenedor al puerto del host
    environment:
      POSTGRES_DB: usuarios  # Cambia esto al nombre de tu base de datos
      POSTGRES_USER: postgres    # Cambia esto al nombre de usuario de PostgreSQL
      POSTGRES_PASSWORD: postgres  # Cambia esto a la contraseña de PostgreSQL

